-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "traffic" (
	"created_at" timestamp with time zone PRIMARY KEY DEFAULT now() NOT NULL,
	"user_id" uuid NOT NULL,
	"success" boolean NOT NULL,
	"user_name" text
);
--> statement-breakpoint
ALTER TABLE "traffic" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text,
	"email" text NOT NULL,
	"phone" text,
	"address" text,
	"postal_code" text,
	"city" text,
	"country" text DEFAULT 'CH' NOT NULL,
	"address_verified" smallint DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"phone_verified" boolean DEFAULT false NOT NULL,
	"password_hash" text,
	"avatar_url" text,
	"total_spent" numeric(10, 2) DEFAULT '0.00',
	"email_verified" boolean DEFAULT false,
	"role" text,
	CONSTRAINT "users_email_unique" UNIQUE("email"),
	CONSTRAINT "users_new_phone_key" UNIQUE("phone")
);
--> statement-breakpoint
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "sales" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ventes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"client_name" text,
	"user_id" uuid,
	"receipt" text,
	"price" bigint DEFAULT '0',
	"items_json" jsonb,
	"expires_at" timestamp with time zone,
	"order_ref" text
);
--> statement-breakpoint
ALTER TABLE "sales" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "news" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"category" text NOT NULL,
	"type" text,
	"title" text NOT NULL,
	"subtitle" text,
	"content" text,
	"image1" text,
	"image2" text,
	"is_published" boolean NOT NULL,
	"link" text,
	"link_name" text,
	CONSTRAINT "news_title_key" UNIQUE("title")
);
--> statement-breakpoint
ALTER TABLE "news" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "reports" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid,
	"type" text NOT NULL,
	"description" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"resolved_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "reports" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "producer_deliveries" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"producer_id" uuid NOT NULL,
	"items" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"notes" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "producer_deliveries_status_check" CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'cancelled'::text]))
);
--> statement-breakpoint
CREATE TABLE "producer_invoices" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"producer_id" uuid NOT NULL,
	"delivery_id" uuid,
	"invoice_number" text NOT NULL,
	"items" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"amount_chf" numeric(10, 2) NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"notes" text,
	"sent_at" timestamp with time zone,
	"paid_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "producer_invoices_status_check" CHECK (status = ANY (ARRAY['draft'::text, 'sent'::text, 'paid'::text]))
);
--> statement-breakpoint
CREATE TABLE "saved_lists" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"name" text NOT NULL,
	"items" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "saved_lists" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "bulk_orders" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"contact_name" text NOT NULL,
	"contact_email" text,
	"contact_phone" text,
	"event_description" text,
	"event_date" date,
	"items" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"subtotal" integer DEFAULT 0 NOT NULL,
	"discount_rate" integer DEFAULT 0 NOT NULL,
	"total" integer DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"stripe_payment_link" text,
	"admin_notes" text,
	"resolved_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "bulk_orders" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "producer_proposals" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"producer_id" uuid NOT NULL,
	"type" text NOT NULL,
	"product_id" text,
	"data" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"admin_note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "producer_proposals_status_check" CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
	CONSTRAINT "producer_proposals_type_check" CHECK (type = ANY (ARRAY['new_product'::text, 'price_change'::text]))
);
--> statement-breakpoint
CREATE TABLE "login_attempts" (
	"identifier" text PRIMARY KEY NOT NULL,
	"failed_count" integer DEFAULT 0 NOT NULL,
	"first_failed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"locked_until" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "login_attempts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "product_list" (
	"name" text,
	"cadar" text,
	"quantity" text,
	"category" text,
	"producer" text,
	"barcode" text,
	"price_chf" text,
	"image_url" text,
	"description" text,
	"stock_shelf" text,
	"stock_back" text,
	"is_active" boolean DEFAULT true,
	"updated_at" text,
	"badge" text,
	"Prix unit. [CHF]" text,
	"Nbre. articles" text,
	"Lot" text,
	"Prix d'achat [CHF]" text,
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"expiry_date" date,
	"discount_percent" numeric(5, 2),
	"discount_until" date
);
--> statement-breakpoint
ALTER TABLE "product_list" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "producers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"contact_name" text,
	"email" text NOT NULL,
	"password_hash" text NOT NULL,
	"phone" text,
	"address" text,
	"description" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"user_id" uuid,
	CONSTRAINT "producers_email_key" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "reports" ADD CONSTRAINT "reports_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "producer_deliveries" ADD CONSTRAINT "producer_deliveries_producer_id_fkey" FOREIGN KEY ("producer_id") REFERENCES "public"."producers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "producer_invoices" ADD CONSTRAINT "producer_invoices_delivery_id_fkey" FOREIGN KEY ("delivery_id") REFERENCES "public"."producer_deliveries"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "producer_invoices" ADD CONSTRAINT "producer_invoices_producer_id_fkey" FOREIGN KEY ("producer_id") REFERENCES "public"."producers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "saved_lists" ADD CONSTRAINT "saved_lists_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "producer_proposals" ADD CONSTRAINT "producer_proposals_producer_id_fkey" FOREIGN KEY ("producer_id") REFERENCES "public"."producers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "producers" ADD CONSTRAINT "producers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_users_city" ON "users" USING btree ("city" text_ops);--> statement-breakpoint
CREATE INDEX "idx_users_phone" ON "users" USING btree ("phone" text_ops);--> statement-breakpoint
CREATE INDEX "idx_users_postal_code" ON "users" USING btree ("postal_code" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "sales_order_ref_key" ON "sales" USING btree ("order_ref" text_ops);--> statement-breakpoint
CREATE INDEX "idx_producer_proposals_producer" ON "producer_proposals" USING btree ("producer_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_producer_proposals_status" ON "producer_proposals" USING btree ("status" text_ops);--> statement-breakpoint
CREATE INDEX "producers_user_id_idx" ON "producers" USING btree ("user_id" uuid_ops);--> statement-breakpoint
CREATE POLICY "Users can insert own profile" ON "users" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((( SELECT auth.uid() AS uid) = id));--> statement-breakpoint
CREATE POLICY "Users can insert their own profile" ON "users" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
CREATE POLICY "Users can read own profile" ON "users" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "Users can read their own profile" ON "users" AS PERMISSIVE FOR SELECT TO public;--> statement-breakpoint
CREATE POLICY "Users can update own profile" ON "users" AS PERMISSIVE FOR UPDATE TO "authenticated";--> statement-breakpoint
CREATE POLICY "Users can update their own profile" ON "users" AS PERMISSIVE FOR UPDATE TO public;
*/